# Generated by Django 5.2.1 on 2025-05-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
