# Generated by Django 5.2.1 on 2025-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_alter_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='admin_comment',
            field=models.CharField(default='Nothing', max_length=2000),
        ),
    ]
