# Generated by Django 5.2.1 on 2025-05-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
